Repository sungha00/Prog-rangers, pull requests merged in 2023-08, with the labels that each got.

#3 Chore: frontend project setting
  .gitignore
  package.json
  public/index.html
  src/App.js
  src/apis/index.js
  src/assets/index.js
  src/components/index.js
  src/context/index.js
  src/hooks/index.js
  src/index.css
  src/pages/index.js
  src/store/index.js
  src/utils/index.js
  yarn.lock
Labels: Chore

#5 Feat: 라우팅 기능 추가
  src/App.js
  src/components/Navbar.jsx
  src/index.js
  src/pages/Home.jsx
  src/pages/MyPage.jsx
  src/pages/NotFound.jsx
  src/pages/Problems.jsx
  src/pages/Profile.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/pages/SolutionDetail.jsx
  src/pages/Solutions.jsx
  src/pages/index.js
Labels: Chore

#7 chore: 스타일 디렉토리 추가
  src/styles/index.js
Labels: Feat

#14 design: main page layout
  src/components/Home/Gallery.jsx
  src/pages/Home.jsx
  src/styles/MainPage.js
Labels: Feat

#16 header-nav-text-edit
  src/components/AfterLoginNav.jsx
  src/components/BeforeLoginNav.jsx
Labels: Docs

#18 feat: add main page eventListener
  src/components/Home/Gallery.jsx
  src/index.js
  src/pages/Home.jsx
Labels: Feat

#20 chore: update project setting
  craco.config.js
  package.json
  src/components/AfterLoginNav.jsx
  src/components/BeforeLoginNav.jsx
  src/components/Header.jsx
  src/components/Home/Gallery.jsx
  src/components/SignUp/SignUpForm.jsx
  src/pages/Home.jsx
  src/pages/SignUp.jsx
  src/styles/MainPage.js
  src/styles/headerStyle.jsx
  src/styles/signUpPage.js
  yarn.lock
Labels: Chore
